### ISSUE TITLE
Custom Gateway

### ISSUE THREAD

**Issue by xKliment** [solaceten/WHMCS-Gateway-Fees#7]
Hello, I wanted to know on how to add another Payment Gateway.
I have a custom Module that adds a Payment Gateway for Paysafecard they charge 15%.

**Comment by solaceten** [comment]
Hi, if you take a look at the [gateway_fees.php around line 20](https://github.com/solaceten/WHMCS-Gateway-Fees/blob/41ed29599690dac4e64f3f374b654523ff6b26a9/modules/addons/gateway_fees/gateway_fees.php#L23), you will see that this plugin should work for all gateways. You just need to configure it in admin under your WHMCS > Setup -> Addon Modules, active and configure.  Info in the [readme](https://github.com/solaceten/WHMCS-Gateway-Fees/blob/master/README.md)
